// This type is automatically generated by Supabase and should be updated
// whenever your database schema changes. You can generate this type by running:
// npx supabase gen types typescript --project-id your-project-id > types/supabase.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Add your database table types here
      // Example:
      // profiles: {
      //   Row: {}
      //   Insert: {}
      //   Update: {}
      // }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
